---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: supertarto.apache
    - role: supertarto.mariadb
    - role: supertarto.php
    - role: supertarto.glpi
  vars:
    php_packages:
      - php{{php_default_version_debian}}
      - php{{php_default_version_debian}}-gd
      - php{{php_default_version_debian}}-mysql
      - php{{php_default_version_debian}}-curl
      - php{{php_default_version_debian}}-imap
      - php-json
      - php{{php_default_version_debian}}-ldap
      - php{{php_default_version_debian}}-mbstring
      - php{{php_default_version_debian}}-xml
      - php{{php_default_version_debian}}-cli
      - php{{php_default_version_debian}}-xmlrpc
      - php{{php_default_version_debian}}-intl
      - php-apcu
      - php-cas
      - php{{php_default_version_debian}}-zip
      - php{{php_default_version_debian}}-bz2

    glpi_auto_install: true
    glpi_db_host: "localhost"
    glpi_db_port: "3306"
    glpi_db_name: "glpi"
    glpi_db_user: "glpi"
    glpi_db_password: "changeit!"
    apache_create_vhosts: true
    apache_vhosts_filename: "glpi.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        documentroot: "/var/www/glpi"
        serveradmin: admin@localhost
        custom_param: |
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
          LogLevel warn
        directory:
          - path: "/var/www/glpi"
            config: |
              AllowOverride All
              Order deny,allow
              allow from all

    mariadb_use_dump_script: false
    mariadb_databases:
      - name: "{{ glpi_db_name }}"

    mariadb_users:
      - name: "{{ glpi_db_user }}"
        host: "{{ glpi_db_host }}"
        password: "{{ glpi_db_password }}"
        priv: "{{ glpi_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
